/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: ebbe4016149875d3bf7884f67316fd2a)
interface __BaseEnv_Env {
	ASSETS: R2Bucket;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
